services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - ghcr.io/rosegoli/hamster:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.5G"
