services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - ghcr.io/rosegoli/hamster:latest
    restart: always
    env_file:
      - .env
    environment:
      DB_PATH: /app/db/database.db
    privileged: true
    network_mode: "host"
    volumes:
      - ./sessions:/app/sessions
      - ./db:/app/db
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.5G"
