headers = {
    'Accept'             : 'application/json',
    'Accept-Language'    : 'en-US,ru;q=0.9',
    'Content-Type'       : 'application/json',
    'Connection'         : 'keep-alive',
    'Origin'             : 'https://hamsterkombat.io',
    'Referer'            : 'https://hamsterkombat.io/',
    'Sec-Fetch-Dest'     : 'empty',
    'Sec-Fetch-Mode'     : 'cors',
    'Sec-Fetch-Site'     : 'same-site',
    'Sec-Ch-Ua'          : '"Android WebView";v="125", "Chromium";v="125", "Not.A/Brand";v="24"',
    'Sec-Ch-Ua-mobile'   : '?1',
    'Sec-Ch-Ua-platform' : '"Android"',
    "User-Agent"         : "Mozilla/5.0 (Linux; Android 11; SM-A305F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.147 Mobile Safari/537.36",
}