name: build
run-name: "🧪 Build "

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: build-ci
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rosegoli/hamster

jobs:
  build-tswap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    name: "🛖 Build and release docker image"

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildX
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          network: host
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref == 'refs/heads/master' && 'latest' || github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
